#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Financiero
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FinanzasDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTransacciones(Transacciones instance);
    partial void UpdateTransacciones(Transacciones instance);
    partial void DeleteTransacciones(Transacciones instance);
    partial void InsertLimites(Limites instance);
    partial void UpdateLimites(Limites instance);
    partial void DeleteLimites(Limites instance);
    partial void InsertMetasAhorro(MetasAhorro instance);
    partial void UpdateMetasAhorro(MetasAhorro instance);
    partial void DeleteMetasAhorro(MetasAhorro instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Proyecto_Financiero.Properties.Settings.Default.FinanzasDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_datagrid1> vw_datagrid1
		{
			get
			{
				return this.GetTable<vw_datagrid1>();
			}
		}
		
		public System.Data.Linq.Table<Transacciones> Transacciones
		{
			get
			{
				return this.GetTable<Transacciones>();
			}
		}
		
		public System.Data.Linq.Table<Limites> Limites
		{
			get
			{
				return this.GetTable<Limites>();
			}
		}
		
		public System.Data.Linq.Table<MetasAhorro> MetasAhorro
		{
			get
			{
				return this.GetTable<MetasAhorro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_datagrid1")]
	public partial class vw_datagrid1
	{
		
		private System.Nullable<System.DateTime> _Fecha_Operacion;
		
		private string _Concepto;
		
		private string _Categoria;
		
		private System.Nullable<decimal> _Importe;
		
		private System.Nullable<decimal> _Saldo;
		
		public vw_datagrid1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Operacion", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Operacion
		{
			get
			{
				return this._Fecha_Operacion;
			}
			set
			{
				if ((this._Fecha_Operacion != value))
				{
					this._Fecha_Operacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(300)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this._Importe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this._Saldo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transacciones")]
	public partial class Transacciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _Fecha_Operacion;
		
		private System.Nullable<System.DateTime> _Fecha_Valor;
		
		private string _Concepto;
		
		private string _Categoria;
		
		private System.Nullable<decimal> _Importe;
		
		private System.Nullable<decimal> _Saldo;
		
		private string _Divisa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFecha_OperacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_OperacionChanged();
    partial void OnFecha_ValorChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ValorChanged();
    partial void OnConceptoChanging(string value);
    partial void OnConceptoChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnImporteChanging(System.Nullable<decimal> value);
    partial void OnImporteChanged();
    partial void OnSaldoChanging(System.Nullable<decimal> value);
    partial void OnSaldoChanged();
    partial void OnDivisaChanging(string value);
    partial void OnDivisaChanged();
    #endregion
		
		public Transacciones()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Operacion", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Operacion
		{
			get
			{
				return this._Fecha_Operacion;
			}
			set
			{
				if ((this._Fecha_Operacion != value))
				{
					this.OnFecha_OperacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Operacion = value;
					this.SendPropertyChanged("Fecha_Operacion");
					this.OnFecha_OperacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Valor", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Valor
		{
			get
			{
				return this._Fecha_Valor;
			}
			set
			{
				if ((this._Fecha_Valor != value))
				{
					this.OnFecha_ValorChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Valor = value;
					this.SendPropertyChanged("Fecha_Valor");
					this.OnFecha_ValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(300)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this.OnConceptoChanging(value);
					this.SendPropertyChanging();
					this._Concepto = value;
					this.SendPropertyChanged("Concepto");
					this.OnConceptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(100)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Divisa", DbType="VarChar(5)")]
		public string Divisa
		{
			get
			{
				return this._Divisa;
			}
			set
			{
				if ((this._Divisa != value))
				{
					this.OnDivisaChanging(value);
					this.SendPropertyChanging();
					this._Divisa = value;
					this.SendPropertyChanged("Divisa");
					this.OnDivisaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Limites")]
	public partial class Limites : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Categoria;
		
		private decimal _Limite;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnLimiteChanging(decimal value);
    partial void OnLimiteChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    #endregion
		
		public Limites()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limite", DbType="Decimal(18,2) NOT NULL")]
		public decimal Limite
		{
			get
			{
				return this._Limite;
			}
			set
			{
				if ((this._Limite != value))
				{
					this.OnLimiteChanging(value);
					this.SendPropertyChanging();
					this._Limite = value;
					this.SendPropertyChanged("Limite");
					this.OnLimiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MetasAhorro")]
	public partial class MetasAhorro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Concepto;
		
		private decimal _MontoObjetivo;
		
		private bool _Completada;
		
		private System.Nullable<System.DateTime> _FechaCreacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnConceptoChanging(string value);
    partial void OnConceptoChanged();
    partial void OnMontoObjetivoChanging(decimal value);
    partial void OnMontoObjetivoChanged();
    partial void OnCompletadaChanging(bool value);
    partial void OnCompletadaChanged();
    partial void OnFechaCreacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public MetasAhorro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this.OnConceptoChanging(value);
					this.SendPropertyChanging();
					this._Concepto = value;
					this.SendPropertyChanged("Concepto");
					this.OnConceptoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoObjetivo", DbType="Decimal(18,2) NOT NULL")]
		public decimal MontoObjetivo
		{
			get
			{
				return this._MontoObjetivo;
			}
			set
			{
				if ((this._MontoObjetivo != value))
				{
					this.OnMontoObjetivoChanging(value);
					this.SendPropertyChanging();
					this._MontoObjetivo = value;
					this.SendPropertyChanged("MontoObjetivo");
					this.OnMontoObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completada", DbType="Bit NOT NULL")]
		public bool Completada
		{
			get
			{
				return this._Completada;
			}
			set
			{
				if ((this._Completada != value))
				{
					this.OnCompletadaChanging(value);
					this.SendPropertyChanging();
					this._Completada = value;
					this.SendPropertyChanged("Completada");
					this.OnCompletadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
